# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/api.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10protos/api.proto\x12\x03\x61pi\"\x1c\n\nApiRequest\x12\x0e\n\x06length\x18\x01 \x01(\x05\"$\n\x07UserDto\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"!\n\x05Users\x12\x18\n\x05users\x18\x01 \x03(\x0b\x32\t.api.User\"-\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x05Hello\x12\x0f\n\x07message\x18\x01 \x01(\t2\x87\x01\n\x03\x41pi\x12+\n\x08sayHello\x12\x11.api.HelloRequest\x1a\n.api.Hello\"\x00\x12\'\n\x06getAll\x12\x0f.api.ApiRequest\x1a\n.api.Users\"\x00\x12*\n\tgetStream\x12\x0c.api.UserDto\x1a\t.api.User\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.api_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APIREQUEST']._serialized_start=25
  _globals['_APIREQUEST']._serialized_end=53
  _globals['_USERDTO']._serialized_start=55
  _globals['_USERDTO']._serialized_end=91
  _globals['_USERS']._serialized_start=93
  _globals['_USERS']._serialized_end=126
  _globals['_USER']._serialized_start=128
  _globals['_USER']._serialized_end=173
  _globals['_HELLOREQUEST']._serialized_start=175
  _globals['_HELLOREQUEST']._serialized_end=203
  _globals['_HELLO']._serialized_start=205
  _globals['_HELLO']._serialized_end=229
  _globals['_API']._serialized_start=232
  _globals['_API']._serialized_end=367
# @@protoc_insertion_point(module_scope)
